PORTIFOLIO/AboutPage/routes.py
from flask import Blueprint, render_template

aboutPage = Blueprint('aboutPage', __name__)


@aboutPage.route("/About")
def aboutpage():
    return render_template("About.html")

PORTIFOLIO/AlbertCaseStudy/routes.py
from flask import Blueprint, render_template

AlbertStudyCase = Blueprint('AlbertStudyCase', __name__)


@AlbertStudyCase.route("/Albert-StudyCase")
def AlbertCaseStudy():
    return render_template("AlbertCaseStudy.html")

PORTIFOLIO/ContactPage/routes.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, current_app
from flask_mail import Message
from PORTIFOLIO import mail

contactPage = Blueprint('contactPage', __name__)

@contactPage.route('/contact', methods=['GET', 'POST'])
def contact():
    if request.method == 'POST':
        subject = request.form['subject']
        user_email = request.form['email']
        body = request.form['message']

        try:
            # Set a no-reply address as the sender
            no_reply_address = "no-reply@example.com" 

            # Create the message
            msg = Message(subject, sender=no_reply_address, recipients=["karinna.rocha2@gmail.com"])
            msg.body = f"From: {user_email}\n\n{body}"

            # Set the reply-to to the user's email
            msg.reply_to = user_email

            # Send the email
            mail.send(msg)
            flash('Message sent successfully!')
        except Exception as e:
            flash(f'An error occurred: {str(e)}')
            print(f'Error: {str(e)}')

        return redirect(url_for('contactPage.contact'))
    
    return render_template('Contact.html')

PORTIFOLIO/DaniellyCaseStudy/routes.py
from flask import Blueprint, render_template

DaniellyStudyCase = Blueprint('DaniellyStudyCase',__name__)

@DaniellyStudyCase.route("/Danielly-StudyCase")
def DaniellyCaseStudy():
    return render_template("DaniellyCaseStudy.html")

PORTIFOLIO/HellenCaseStudy/routes.py
from flask import Blueprint, render_template

HellenStudyCase = Blueprint('HellenStudyCase',__name__)

@HellenStudyCase.route("/Hellen-StudyCase")
def HellenCaseStudy():
    return render_template("HellenCaseStudy.html")

PORTIFOLIO/IndexPage/routes.py
from flask import render_template, Blueprint

indexPage = Blueprint('indexPage', __name__)


@indexPage.route("/")
def home():
    return render_template("index.html")

PORTIFOLIO/__init__.py
from flask import Flask
from flask_mail import Mail
from PORTIFOLIO.config import Config

mail = Mail()

def create_app():

    app = Flask(__name__)

    app.config.from_object(Config)
    mail.init_app(app)
    
    from .IndexPage.routes import indexPage
    from .AboutPage.routes import aboutPage
    from .ContactPage.routes import contactPage
    from .AlbertCaseStudy.routes import AlbertStudyCase 
    from .DaniellyCaseStudy.routes import DaniellyStudyCase
    from .HellenCaseStudy.routes import HellenStudyCase

    app.register_blueprint(indexPage)
    app.register_blueprint(AlbertStudyCase)
    app.register_blueprint(aboutPage)
    app.register_blueprint(contactPage)
    app.register_blueprint(DaniellyStudyCase)
    app.register_blueprint(HellenStudyCase)

    return app

PORTIFOLIO/templates/About.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>My Work</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='style.css') }}"
    />
  </head>
  <body class="fullpage">
    <!-- NAV starts -->
    <nav class="navspacecontainer">
      <div class="navspace">
        <div class="nav-line"></div>
        <div>
          <a href="{{ url_for('indexPage.home') }}">HOME</a>
        </div>
        <div class="copyright">© | 2024</div>
      </div>
    </nav>
    <!-- TITLE starts -->
    <div class="division">
      <h1 class="Abouttitle animated-textUp">About</h1>
      <img
        src="static/uploads/Photo.jpg"
        alt="Photo"
        width="370"
        height="500"
        class="photoadjust"
      />
    </div>
    <div class="Aboutmainbody">
      <h2 class="AboutSubtitle">
        Hi! My name is Karinna , I'm a problem solver but also a maker.
      </h2>
      <div class="selfDescription">
        A lover of technology and a logical thinker, I come from an architecture
        background where I had the pleasure of working for two years. I
        discovered that architecture wasn't my passion, and I wanted more. I
        moved to America for a new challenge in my life and immersed myself in a
        Computer Information Systems college. I became the first person in my
        family to earn an American college degree and discover new skills. I was
        solving problems, and my past career in architecture helped me get where
        I am today. I took advantage of learning Python, HTML, CSS, JavaScript,
        and React Native, and implemented my design mindset into my software
        development. My logical thinking allowed me to find the most efficient
        ways to complete tasks. Everything I have done, small or big, has been a
        vital stepping stone.
        <br /><br />
        Known as NurVIX on the internet, I started my streaming channel at the
        beginning of COVID-19. What began as a hobby became much more. I
        combined my passion for tech with my love of making connections. I
        started playing video games and ended up splitting my time coding with
        my community, where we all share knowledge and push each other forward.
        With a lot of hard work and time invested, I grew a channel that now
        reaches 3,500 followers and was fortunate enough to build an awesome and
        supportive community worldwide.
        <br /><br />
        As a Jiu-jitsu lover, aside from technology, I have a passion for
        martial arts. It is a part of me where I learn every day to be humble,
        respectful, and grateful. It teaches me resilience, efficiency, and
        critical thinking, which I constantly implement in my daily life.
        <br /><br />
        You will probably hear me say a lot:
        <br /><br />
        "We got this!"
        <br /><br />
      </div>
    </div>
    <div class="divSubTitles">
      <h3 class="subTitles">Experience</h3>
      <span class="skillsdescription">
        - Associates in Information technology
        <br />
        - Bachelor in Computer Information System
        <br />
        - 4 years in Software Development, Web Design, SEO Strategy, Mobile
        Devices
        <br />
        <br />
        Within these 4 years, I have:
        <br />
        <br />
        - 4 years experience in Software designing
        <br />
        - 3 years experience in Webflow Development
        <br />
        - 3 years in Mobile Devices
      </span>
      <h3 class="subTitles">Skills</h3>
      <span class="skillsdescription">
        Technical Skills:
        <br />
        <br />
        UI/UX Design / SEO Strategy / Product Management / Mobile Device
        Architecture / Design Sprints / Python / HTML and CSS / React Native /
        Webflow Development
        <br />
        <br />
        Personal Skills:
        <br />
        <br />
        Photography / Jiu jitsu / Guitar / Archery / Chess / Cooking
      </span>
      <div class="buttonbox">
        <a
          href="../static/uploads/Karinna Rocha Resume.pdf"
          target="_blank"
          class="button w-button"
          >My CV</a
        >
      </div>
    </div>
  </body>
</html>

PORTIFOLIO/templates/AlbertCaseStudy.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>My Work</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='style.css') }}"
    />
  </head>
  <body class="fullpage">
    <!-- NAV starts -->
    <nav class="navspacecontainer">
      <div class="navspace">
        <div class="nav-line"></div>
        <div>
          <a href="{{ url_for('indexPage.home') }}">HOME</a>
        </div>
        <div class="copyright">© | 2024</div>
      </div>
    </nav>
    <!-- BODY OF STUDY CASE starts -->
    <section>
      <div class="StudycaseTitleSection">
        <h1 class="StudycaseTitle">Albert-Coaching</h1>
        <h3 class="StudyCaseSubTitle">
          This page contains the case study of Albert-Coaching Website which
          includes the Project Overview, Tools Used and Live Links to the
          official product.
        </h3>
      </div>
      <div class="StudycaseButton">
        <a href="wwww.albert-coaching.com" target="_blank">
          <button class="button w-button" type="button">Website Link</button></a
        >
      </div>
      <div class="CaseStudyContainer">
        <div class="CaseStudyEdge">
          <img
            src="{{ url_for('static', filename='uploads/albertcoachingsidescreen.png') }}"
            alt="albert Web"
            class="imageCaseStudyEdges"
          />
        </div>
        <div class="CaseStudyCenter">
          <img
            src="{{ url_for('static', filename='uploads/Albertmainpage.png') }}"
            alt="albert Web"
            class="imageCaseStudycenter"
          />
        </div>
        <div class="CaseStudyEdge">
          <img
            src="{{ url_for('static', filename='uploads/Albertprogrampage.png') }}"
            alt="albert Web"
            class="imageCaseStudyEdges"
          />
        </div>
      </div>
      <div class="StudocaseDescriptionSection">
        <div class="StudyCase-desc">
          <h2 class="DescTitleStudyCase">Albert-Coaching</h2>
          <p class="DescStudyCase">
            Well known high performace body builder, with a large presence for
            having over 20 thousand followers on social media , my client wanted
            a website that would represent his personality with the goal to grow
            your sucessful online coaching business, I designed the website with
            some touches the client asked was looking for: Clean and Classy.
            <br />
            <br />
            With the passion of building responsive websites from scratch, I
            designed the UI and UX of this website focusing on the best
            peformance user friendly and lower coast for the client, resulting a
            higher memberships registration to his training business.
          </p>
        </div>
        <div class="StudyCase-toolsused">
          <h2 class="DescTitleStudyCase">Tools Used</h2>
          <div class="DescStudyCase">
            <div class="TollsIcons">
              <h4>Python</h4>
            </div>
            <div class="TollsIcons">
              <p>React</p>
            </div>
            <div class="TollsIcons">
              <h4>CSS</h4>
            </div>
            <div class="TollsIcons">
              <h4>SASS</h4>
            </div>
            <div class="TollsIcons">
              <h4>Heroku</h4>
            </div>
            <div class="TollsIcons">
              <h4>git CLI</h4>
            </div>
          </div>
        </div>
      </div>
      <div class="StudycaseButton">
        <a href="https://wwww.albert-coaching.com" target="_blank">
          <button class="button w-button" type="button">Website Link</button></a
        >
      </div>
      <footer class="Spacefooter">
        <div class="flexLeftsideFooter">
          <h2>Karinna Rocha</h2>
          <h4>
            Full Stack developer with the creative mind of designing inovated
            and responsive softwares
          </h4>
        </div>
        <div class="flexRightsideFooter">
          <h2>Socials</h2>
        </div>
      </footer>
    </section>
  </body>
</html>

PORTIFOLIO/templates/ClassCourseCaseStudy.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>My Work</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='style.css') }}"
    />
  </head>
  <body class="fullpage">
    <!-- NAV starts -->
    <nav class="navspacecontainer">
      <div class="navspace">
        <div class="nav-line"></div>
        <div>
          <a href="{{ url_for('indexPage.home') }}">HOME</a>
        </div>
        <div class="copyright">© | 2024</div>
      </div>
    </nav>
    <!-- BODY OF STUDY CASE starts -->
    <section>
      <div class="StudycaseTitleSection">
        <h1>Albert-Coaching</h1>
        <h4>
          This page contains the case study of Albert-coaching website which
          includes the Project Overview, Tools Used and Live Links to the
          official product.
        </h4>
      </div>
    </section>
  </body>
</html>

PORTIFOLIO/templates/Contact.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>CONTACT ME</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='style.css') }}"
    />
  </head>
  <body class="fullpage">
    <!-- NAV starts -->
    <nav class="navspacecontainer">
      <div class="navspace">
        <div class="nav-line"></div>
        <div>
          <a href="{{ url_for('indexPage.home') }}">HOME</a>
        </div>
        <div class="copyright">© | 2024</div>
      </div>
    </nav>
    <div class="ContactTitle">Contact me!</div>
    <div class="ContactContent">The best way to get connected with me!</div>
    <div class="contactForm">
      <form action="{{ url_for('contactPage.contact') }}" method="POST">
        <label for="email">Email</label>
        <input type="email" id="email" name="email" required />

        <label for="subject">Subject</label>
        <input type="text" id="subject" name="subject" required />

        <label for="message">Message</label>
        <textarea
          id="message"
          name="message"
          rows="4"
          cols="50"
          required
          class="messagebox"
        ></textarea>

        <button class="button w-button" type="submit">Send Email</button>
      </form>
    </div>
    {% with messages=get_flashed_messages(with_categories=true) %} {% if
    messages %}
    <ul>
      {% for category, message in messages %}
      <li class="{{ category }}">{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %} {% endwith %}
  </body>
</html>

PORTIFOLIO/templates/DaniellyCaseStudy.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>My Work</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='style.css') }}"
    />
  </head>
  <body class="fullpage">
    <!-- NAV starts -->
    <nav class="navspacecontainer">
      <div class="navspace">
        <div class="nav-line"></div>
        <div>
          <a href="{{ url_for('indexPage.home') }}">HOME</a>
        </div>
        <div class="copyright">© | 2024</div>
      </div>
    </nav>
    <!-- BODY OF STUDY CASE starts -->
    <section>
      <div class="StudycaseTitleSection">
        <h1 class="StudycaseTitle">Danielly's Fitness</h1>
        <h3 class="StudyCaseSubTitle">
          This page contains the case study of Danielly's Fitness Website which
          includes the Project Overview, Tools Used and Live Links to the
          official product.
        </h3>
      </div>
      <div class="StudycaseButton">
        <a href="https://www.daniellysfitness.com" target="_blank">
          <button class="button w-button" type="button">Website Link</button></a
        >
      </div>
      <div class="CaseStudyContainer">
        <div class="CaseStudyEdge">
          <img
            src="{{ url_for('static', filename='uploads/daniellysideleft.png') }}"
            alt="albert Web"
            class="imageCaseStudyEdges"
          />
        </div>
        <div class="CaseStudyCenter">
          <img
            src="{{ url_for('static', filename='uploads/Daniellymainpage.png') }}"
            alt="albert Web"
            class="imageCaseStudycenter"
          />
        </div>
        <div class="CaseStudyEdge">
          <img
            src="{{ url_for('static', filename='uploads/daniellysidescreen.png') }}"
            alt="albert Web"
            class="imageCaseStudyEdges"
          />
        </div>
      </div>
      <div class="StudocaseDescriptionSection">
        <div class="StudyCase-desc">
          <h2 class="DescTitleStudyCase">Danielly's Fitness</h2>
          <p class="DescStudyCase">
            Bringing a vast of knowledge and certifications based on Sports
            medicine and providing many types of programs that you improve life
            quality, This website was one of the greatest UI's I did so far,
            partnering with a skilled team responsable for the development of
            the backend of the website, Danielly's Fitness has been nominated
            and voted in the TOP THREE TRAINERS IN SONOMA in 2018, 2019, and
            2023 and won FIRST PLACE in the 2020 and 2021 People’s Choice
            Awards.
            <br />
            <br />
            Danielly wanted to bring this modern style with the mindfull
            directing the website into a fitness and wellness enviroment just
            like her program offering in her site, and the outcome was amazing.
          </p>
        </div>
        <div class="StudyCase-toolsused">
          <h2 class="DescTitleStudyCase">Tools Used</h2>
          <div class="DescStudyCase">
            <div class="TollsIcons">
              <h4>PHP</h4>
            </div>
            <div class="TollsIcons">
              <p>Wordpress</p>
            </div>
            <div class="TollsIcons">
              <h4>HTML</h4>
            </div>
            <div class="TollsIcons">
              <h4>CSS</h4>
            </div>
            <div class="TollsIcons">
              <h4>JavaScript</h4>
            </div>
          </div>
        </div>
      </div>
      <div class="StudycaseButton">
        <a href="https://www.daniellysfitness.com" target="_blank">
          <button class="button w-button" type="button">Website Link</button></a
        >
      </div>
      <footer class="Spacefooter">
        <div class="flexLeftsideFooter">
          <h2>Karinna Rocha</h2>
          <h4>
            Full Stack developer with the creative mind of designing inovated
            and responsive softwares
          </h4>
        </div>
        <div class="flexRightsideFooter">
          <h2>Socials</h2>
        </div>
      </footer>
    </section>
  </body>
</html>

PORTIFOLIO/templates/HellenCaseStudy.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>My Work</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='style.css') }}"
    />
  </head>
  <body class="fullpage">
    <!-- NAV starts -->
    <nav class="navspacecontainer">
      <div class="navspace">
        <div class="nav-line"></div>
        <div>
          <a href="{{ url_for('indexPage.home') }}">HOME</a>
        </div>
        <div class="copyright">© | 2024</div>
      </div>
    </nav>
    <!-- BODY OF STUDY CASE starts -->
    <section class="fullpage">
      <div class="StudycaseTitleSection">
        <div class="StudycaseTitle">Hellen Architect</div>
        <h3 class="StudyCaseSubTitle">
          This page contains the case study of Hellen Rocha Website which
          includes the Project Overview, Tools Used and Live Links to the
          official product.
        </h3>
      </div>
      <div class="StudycaseButton">
        <a
          href="https://www.figma.com/design/DJgWrK82cQOE0lUpErKXFC/Hellen-Rocha?node-id=0-1&p=f&t=UeS3lVzIArvDW69L-0"
          target="_blank"
        >
          <button class="button w-button" type="button">Website Link</button></a
        >
      </div>
      <div class="CaseStudyContainer">
        <div class="CaseStudyEdge">
          <img
            src="{{ url_for('static', filename='uploads/hellensideleft.png') }}"
            alt="albert Web"
            class="imageCaseStudyEdges"
          />
        </div>
        <div class="CaseStudyCenter">
          <img
            src="{{ url_for('static', filename='uploads/HellenMainPage.png') }}"
            alt="albert Web"
            class="imageCaseStudycenter"
          />
        </div>
        <div class="CaseStudyEdge">
          <img
            src="{{ url_for('static', filename='uploads/hellensideright.png') }}"
            alt="albert Web"
            class="imageCaseStudyEdges"
          />
        </div>
      </div>
      <div class="StudocaseDescriptionSection">
        <div class="StudyCase-desc">
          <h2 class="DescTitleStudyCase">Hallen Rocha</h2>
          <p class="DescStudyCase">
            Responsable for the UI/UX of this classic and modern mixture of
            website, Hellen is a talented Architect from Brazil that needed a
            website to showcase her vast portifolio though her career, Hellen
            wanted her website clean with the minimum or reading, but focusing
            on visual, pictures and desings
            <br />
            <br />
          </p>
        </div>
        <div class="StudyCase-toolsused">
          <h2 class="DescTitleStudyCase">Tools Used</h2>
          <div class="DescStudyCase">
            <div class="TollsIcons">
              <h4>Python</h4>
            </div>
            <div class="TollsIcons">
              <p>React</p>
            </div>
            <div class="TollsIcons">
              <h4>CSS</h4>
            </div>
            <div class="TollsIcons">
              <h4>Figma</h4>
            </div>
            <div class="TollsIcons">
              <h4>Canva</h4>
            </div>
          </div>
        </div>
      </div>
      <div class="StudycaseButton">
        <a
          href="https://www.figma.com/design/DJgWrK82cQOE0lUpErKXFC/Hellen-Rocha?node-id=0-1&p=f&t=UeS3lVzIArvDW69L-0"
          target="_blank"
        >
          <button class="button w-button" type="button">Website Link</button></a
        >
      </div>
      <footer class="Spacefooter">
        <div class="flexLeftsideFooter">
          <h2>Karinna Rocha</h2>
          <h4>
            Full Stack developer with the creative mind of designing inovated
            and responsive softwares
          </h4>
        </div>
      </footer>
    </section>
  </body>
</html>

PORTIFOLIO/templates/NurvixCaseStudy.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>My Work</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='style.css') }}"
    />
  </head>
  <body id="bodyWork" class="fullpage">
    <!-- NAV starts -->
    <div class="navspace">
      <div class="nav-line"></div>
      <div class="TWicon">
        <a href="{{ url_for('indexPage.home') }}">HOME</a>
      </div>
      <div class="copyright">© | 2024</div>
    </div>
    <!-- BODY OF STUDY CASE starts -->
    <section>
      <div class="StudycaseTitleSection">
        <h1>Albert-Coaching</h1>
        <p></p>
      </div>
    </section>
  </body>
</html>

PORTIFOLIO/templates/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>NurVIX</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='style.css') }}"
    />
  </head>
  <body  class="fullpage">
    <!-- NAV starts -->
    <nav class="navspacecontainer">
      <div class="navspace">
        <div class="nav-line"></div>
        <div>
          <a href="https://www.linkedin.com/in/karinnarocha/" target="_blank"
            >LI</a
          >
        </div>
        <div>
          <a href="https://github.com/karinnarocha" target="_blank">GH</a>
        </div>
        <div>
          <a href="https://x.com/_nurvix" target="_blank">TW</a>
        </div>
        <div class="copyright">© | 2024</div>
      </div>
    </nav>
    <!-- backgroung -->

    <!-- index content -->
    <section class="firstSection">
      <div class="karinnaHeader">Karinna Rocha</div>
      <div class="developerHeader">Software Developer</div>
      <div class="Menu-link">
          <a href="{{ url_for('aboutPage.aboutpage') }}">About</a>
          <a href="{{ url_for('contactPage.contact') }}">Contact</a>
      </div>
    </section>
    <!-- work content -->
    <section class="ExpertiseSession ">
      <div class="divisionExper hidden">
        <div class="Squarespace">
          <div class="expertisetitle">Back-end Dev</div>
          <div class="expertisecontent">
            Experience in Python backend Development using Flask and Django
            Frameworks.
          </div>
        </div>
        <div class="Squarespace">
          <div class="expertisetitle">Front-end Design</div>
          <div class="expertisecontent">
            Passionate about design in general, experience on HTML, JavaScript, CSS and the passion with React.
          </div>
        </div>
        <div class="Squarespace">
          <div class="expertisetitle">Mobile Application</div>
          <div class="expertisecontent">
            Hybrid mobile apps are my way to go on Flutterflow framework or React
            Native.
          </div>
        </div>
      </div>
    </section>
    <!-- INTRO MENU starts -->
    <div class="IntroProjectMenu">
      <p class="IntroTitle">Here you will find some of the personal and clients projects that I created with each project containing its own case study.</p>
    </div>
    <!-- WORK MENU starts -->
    <section class="WorkTitlesSession">
      <div class="divisionWork">
        <div class="myWork">
          <div>My work</div>
        </div>
        <div class="vertical-line fadein"></div>
        <div class="Worklist">
          <a class="workTitle" href="#hellen">HELLEN</a><br />
          <span>Web development</span><br />
          <a class="workTitle" href="#albert">ALBERT</a><br />
          <span>Web development</span><br />
          <a class="workTitle" href="#danielly">DANIELLY</a><br />
          <span>Web Development</span><br />
          <a class="workTitle" href="#nurvix">NURVIX</a><br />
          <span>Web Development</span><br />
          <a class="workTitle" href="#aibeans">AIBEANS</a><br />
          <span>Mobile Development</span><br />
        </div>
      </div>
    </section>
    <!-- WEBSITED TEMPLATES STARTS HERE -->
      <section class="divisionStudycase">
        <div class="divisionTemplatesRight" id = "hellen">
          <img 
              src="{{ url_for('static', filename='uploads/HellenMainPage.png') }}"
              alt="Mercy web"
              class="imageWebsiteRight"
            />
          <div class="ProjectTitleandlink" >
            <span class="project-title">Hellen Rocha</span>
            <br />
            <a href="{{ url_for('HellenStudyCase.HellenCaseStudy') }}" target="_blank">
            <button class="button w-button" type="button">Case Study</button></a>
          </div>
        </div>
        <div class="divisionTemplatesLeft" id = "albert">
              <img 
                src="{{ url_for('static', filename='uploads/Albertmainpage.png') }}"
                alt="albert Web"
                class="imageWebsiteLeft "
              />
          <div class="ProjectTitleandlink" >
            <span class="project-title">Albert-Coaching</span>
            <br />
            <a href="{{ url_for('AlbertStudyCase.AlbertCaseStudy') }}" target="_blank">
            <button class="button w-button" type="button">Case Study</button></a>
          </div>
        </div>
        <div class="divisionTemplatesRight" id = "danielly">
          <img 
              src="{{ url_for('static', filename='uploads/Daniellymainpage.png') }}"
              alt="Danielly web"
              class="imageWebsiteRight"
            />
          <div class="ProjectTitleandlink" >
            <span class="project-title">Danielly's fitness</span>
            <br />
            <a href="{{ url_for('DaniellyStudyCase.DaniellyCaseStudy') }}" target="_blank">
            <button class="button w-button" type="button">Case Study</button></a>
          </div>
        </div>
        <div class="divisionTemplatesLeft" id = "nurvix">
          <img 
            src="{{ url_for('static', filename='uploads/Nurvixmainpage.png') }}"
            alt="NurVIX Page"
            class="imageWebsiteLeft "
          />
          <div class="ProjectTitleandlink" >
            <span class="project-title">NurVIX</span>
            <br />
            <a href="https://www.nurvix.live" target="_blank">
            <button class="button w-button" type="button">Case Study</button></a>
          </div>
        </div>
      </div>
      </section>

     
  <!-- MOBILE APP TEMPLATE STARS HERE -->
  
    <!-- Footer -->
    <footer class="Spacefooter">
      <div class="flexLeftsideFooter">
        <h2>Karinna Rocha</h2>
        <h4>Full Stack developer with the creative mind of designing inovated and responsive softwares</h4>
      </div>
    </footer>
  </body>
</html>

<script>

  document.querySelectorAll('.workTitle').forEach(link => {
    link.addEventListener('click', function(event){
      event.preventDefault();

      const targetId = this.getAttribute("href");
      const targetSection = document.querySelector(targetId);

      if (targetSection){
        targetSection.scrollIntoView({ behavior:'smooth'})
      }
    });
  });



  // JAVASCRIPT FOR SCROLLING AND ANIMATION ON WEB IMAGES
  const observer = new IntersectionObserver((entries) => {
    entries.forEach((entry) => {
      if (entry.isIntersecting) {
        entry.target.classList.add("show");
      } else {
        entry.target.classList.remove("show");
      }
    });
  });

  const hiddenElements = document.querySelectorAll(".hidden");
  hiddenElements.forEach((el) => observer.observe(el));

  function typeWriter(element, text, delay = 50) {
    let index = 0;
    function addLetter() {
      if (index < text.length) {
        element.textContent += text.charAt(index);
        index++;
        setTimeout(() => requestAnimationFrame(addLetter), delay);
      }
    }
    addLetter();
  }

  window.onload = function () {
    const karinnaHeader = document.getElementById("karinnaHeader");
    const developerHeader = document.getElementById("developerHeader");

    developerHeader.textContent = "";
    karinnaHeader.textContent = "";

    // Start typing animations with different delays
    typeWriter(karinnaHeader, "Karinna Rocha", 100);
    typeWriter(developerHeader, "Software Developer", 100);
  };



</script>